### ISSUE TITLE
[Feature Request] Tracker based Bibliothek view (like Foliate for Ebooks)

### ISSUE THREAD

**Issue by fabiscafe** [Rafostar/clapper#60]
Hi. Clapper is a great application for viewing videos. Sadly if I launch it by itself I only get this:
![Bildschirmfoto von 2021-03-30 09-56-46](https://user-images.githubusercontent.com/18744080/112954109-64cba680-913e-11eb-8031-8b9bcf0d6700.png)

Now another project I love is [Foliate](https://github.com/johnfactotum/foliate). And I think a feature of it would fit just fine into Clapper: the Bibliothek view
![grafik](https://user-images.githubusercontent.com/18744080/112955029-4a45fd00-913f-11eb-9ab5-9aca4d96c879.png) where it (can) ask tracker about indexed files and list them.
GNOMEs Video (totem) also provides something like this.

**Comment by Rafostar** [comment]
I do agree that a black screen with little to no buttons until hovered is unappealing, but what, why and how to show there needs some very careful design planning.

**Comment by Rafostar** [comment]
Also keep in mind that unlike books, videos are usually scattered all over your HDD, NAS and HTTP uris. It would be really inefficient (slow) if we would have to scan all those places to make sure that videos are still there in place.

Unlike ebooks readers, people usually just double click the video in Nautilus to launch the app and play it at once or D&D it onto the player window.

Regarding the menu: Foliate has it easy cause books already include covers as a images, so (I think cause I haven't looked into Foliate code) when opening that ebook it just needs take that image as-is and show it as a thumbnail here. In case of videos this is much harder to achieve. One would need to have some sort of video thumbnailer integrated into the player (like Totem does) and use it to extract some random video frame, convert it into image, save to cache folder and use it from there.

**Comment by fabiscafe** [comment]
> why and how to show there needs some very careful design planning.

Yes. Of course! Nobody wants a bad implementation.
> videos are usually scattered all over your HDD, NAS and HTTP uris. It would be really inefficient (slow) if we would have to scan all those places to make sure that videos are still there in place.

That's why tracker. It should keep track of it by itself? At least for everything that is in reach of it. It could start like this, with local files. Sadly I can't tell how online-account could play into that. Because If I look at the gnome photo app, it gathers pictures from different (+network) sources, as well as using the local database.

> Unlike ebooks readers, people usually just double click the video in Nautilus to launch the app and play it at once or D&D it onto the player window.

Hm But here we don't have any choice, since we don't have any usable media player that is application centric, rather then filecentric to begin with. Well, we have totem but here comes that missing design into play that renders the "in app experience" almost useless.

I don't try to pressure you into it. I'm fine in any way and I love your app. It was just an idea how to fill that blank space. 😄

**Comment by Rafostar** [comment]
> I don't try to pressure you into it. I'm fine in any way and I love your app. It was just an idea how to fill that blank space.

Don't worry. I never said no. I also think that when not launched directly from opening file, app should "welcome" user in more appealing manner. Still I do not think that managing a COMPLETE videos library inside the video player would be efficient and easy to use (unlike books). Its been some time since I last used Totem, but from what I remember user had to first browse files, add video to library and then select it to play. I do not think that such extra steps make an enjoyable experience in a video player.

> That's why tracker. It should keep track of it by itself?

Even if that is true, we would still need to iterate over the tracked files list and load the saved thumbnails for videos to show in the window and might end up with doing so for many thousand of video episodes (slowdown).

How about instead of maintaining whole videos library, player shows what user potentially wants - that is: last few unfinished videos (with option to resume) and recently played ones?

**Comment by tabzlock** [comment]
Idk much but something like lollypops managment of thumbnails and albums would probably be cool
Lollypop also seems to have no issue with super large audio collection thumbnails.

**Comment by legacychimera247** [comment]
if you don't want to do something heavy, you can always do like other gnome apps do, like putting a big icon in the middle of the app with a "play some videos" or "play some videos with the icon on the top left corner" , just saying eh...

**Comment by juxuanu** [comment]
What about saving the required file info (generate thumbnail, name, file path (or uri)...) when it is opened? And save it in a sqlite file or something similar and show a list with those entries instead of that blank window?

**Comment by Rafostar** [comment]
A database for unfinished videos is planned, yes. Can be reused later here to show both recent and unfinished videos in single dialog. Not sure if thumbnailer will be necessary.

This is still on TODO list, but right now playback related stuff was prioritized higher and this depends on many things that need to be done in this order:
- [X] libadwaita
- [ ] cache database for unfinished videos
- [ ] access to GTK file tracker
- [ ] implementation of this view

**Comment by Rafostar** [comment]
After some deeper thinking about where does Clapper goes from here, I think that this feature request calls for a separate app after all. The use case of Clapper player is to double click a video file and play it. Simple. But what this FR wants (at least how I understand it) is for users to maintain a library of their files, which not everyone does and should not be forced to do so.

Thus my current plan/suggestion about solving this for people that like maintaining their video collection is:
- [ ] rewrite GstClapper API and make it headers public (already undergoing effort)
- [ ] make a dedicated, separate videos library app that uses our API and embed Clapper player inside it

Then we can expand the new app with file tracker, etc. without breaking Clapper, while leaving and maintaining all Clapper player (and playback) related code here. I believe that this will lead to cleaner code, while Clapper will remain as "simple, easy to use" video player. Having 2 apps covering both use-cases (easy open/play file and videos library). As for empty player window itself, I will probably do some initial status screen with app logo + some text like GNOME HIG wants us to have.

I actually started working on such an app some time ago. But since Clapper requires a LOT more work to make this eventually possible, I haven't touched it in quite a while. The idea is to integrate media parsing with TMDB, in order to show media posters, title, description, etc. where possible. I will likely resume work on it once Clapper is ready for such a feat (be integrated with it). Nonetheless, I am attaching some old, early WIP screenshot of it for reference what I have in mind:

![Screenshot from 2021-11-17 09-48-35](https://user-images.githubusercontent.com/40623528/178974352-26e8e6d6-3653-4c3a-8bb1-e4538fc69b82.png)
